### PR TITLE
Add validation docs

### PR DESCRIPTION
**Pull request by dostuffthatmatters**
I only added `/docs/user-guide/config-validation`.

### CODE REVIEW

**Comment by empicano** [comment]
I'd split the rules up into the existing field type pages, I think they fit well in there. I've done it as an example for the email field, what to you think?

**Comment by dostuffthatmatters** [comment]
Looks really good! You can continue ;)

**Comment by empicano** [comment]
Also, we should probably limit the amount of options one can put into radio and selection fields. I mean, in any case, if your survey has 999 option fields, _maybe_ there's something wrong with the survey? 😄

**Comment by dostuffthatmatters** [comment]
> Also, we should probably limit the amount of options one can put into radio and selection fields. I mean, in any case, if your survey has 999 option fields, _maybe_ there's something wrong with the survey? 😄

Yes, of course we can! I just thought that people who terrorize others with more than 999 fields should not be provided with a working console 😅

**Comment by empicano** [comment]
I upped some limits e.g. for the description and regex parameters, and introduced a max limit for the number of fields. Theoretically we can surely manage those, if the limits were there so that the design on the frontend is right, just change them back 😉

**Comment by dostuffthatmatters** [comment]
Ten thousand characters description? :D That is ten A4 pages of text. None of those limits will screw up the interface :)

I actually think we should have an upper limit for every key. So that a user cannot forcefully overflow the config document with `limit: 1000000...`

**Comment by empicano** [comment]
Good point, I added upper limits for `limit` and `end` -- are there any others? The upper limit for `end` is 01.01.2100, I guess that should suffice for now 😄 As for `limit` I guess we can do more, but we can always increase that one, once we have experience with more load.

**Pull request merged**
